import os
import re
from google import genai

# Initialize client
client = genai.Client(api_key="AIzaSyCQ4fQbiG9p_nuR0GCGNhpu7n8q5dGyV7U")

# Read the log file
with open("security_system.log", "r") as log_file:
    log_data = log_file.read()

# Refined prompt for automated action
action_prompt = f"""
You are an Automated Incident Response AI Agent.
Analyze these system logs and find the malicious IP address that achieved unauthorized shell access.

LOGS:
{log_data}

Provide your response in TWO parts.
Part 1 must be a short paragraph summary of the threat.
Part 2 must be an explicit Windows Firewall netsh command to block that exact IP, wrapped inside a ```cmd ``` code block.
Example format for Part 2:
```cmd
netsh advfirewall firewall add rule name="Block Attacker IP" dir=in action=block remoteip=MALICIOUS_IP_HERE
```
"""

print("Analyzing logs and generating automated mitigation script...")

response = client.models.generate_content(
    model='gemini-2.5-flash',
    contents=action_prompt,
)

print("\n=== AGENT ANALYSIS ===")
print(response.text)

# --- AUTOMATED TOOL USE LAYER ---
# Use Regex to extract the command block generated by Gemini
cmd_match = re.search(r"```cmd\s+(.*?)\s+```", response.text, re.DOTALL)

if cmd_match:
    firewall_command = cmd_match.group(1).strip()
    
    # Write the command to a local batch file
    with open("block_attacker.bat", "w") as script_file:
        script_file.write("@echo off\n")
        script_file.write(f"echo [!] Executing Automated Defense Rule...\n")
        script_file.write(f"{firewall_command}\n")
        script_file.write("echo [+] Malicious IP blocked successfully.\n")
        script_file.write("pause\n")
        
    print("\n⚡ [AUTOMATION ACTIVATED]: Created 'block_attacker.bat' to isolate the threat instantly!")
else:
    print("\n[-] Could not extract firewall command structure.")
